"""anilist accounts

Revision ID: 34a54ec4a8a0
Revises: ea44f47caf5a
Create Date: 2026-09-25 11:07:23.171260

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "34a54ec4a8a0"
down_revision: str | Sequence[str] | None = "ea44f47caf5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("mal_name", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("anilist_user_id", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("anilist_name", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("anilist_token", sa.Text(), nullable=True))
    op.add_column(
        "users", sa.Column("anilist_token_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column("users", "mal_user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("users", "access_token", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("users", "refresh_token", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "users",
        "token_expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.create_unique_constraint(op.f("uq_users_anilist_user_id"), "users", ["anilist_user_id"])
    # ### end Alembic commands ###
    op.execute("UPDATE users SET mal_name = name WHERE mal_user_id IS NOT NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_anilist_user_id"), "users", type_="unique")
    op.alter_column(
        "users",
        "token_expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column("users", "refresh_token", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("users", "access_token", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("users", "mal_user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("users", "anilist_token_expires_at")
    op.drop_column("users", "anilist_token")
    op.drop_column("users", "anilist_name")
    op.drop_column("users", "anilist_user_id")
    op.drop_column("users", "mal_name")
    # ### end Alembic commands ###
