"""stream failures

Revision ID: 5e7efc42613c
Revises: a1adc87f75fe
Create Date: 2026-09-25 20:15:01.005601

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e7efc42613c"
down_revision: str | Sequence[str] | None = "a1adc87f75fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stream_failures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anime_id", sa.Integer(), nullable=False),
        sa.Column("episode", sa.Integer(), nullable=False),
        sa.Column("option_id", sa.String(length=200), nullable=False),
        sa.Column("stream", sa.String(length=100), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stream_failures")),
        sa.UniqueConstraint(
            "anime_id",
            "episode",
            "option_id",
            "stream",
            name=op.f("uq_stream_failures_anime_id_episode_option_id_stream"),
        ),
    )
    op.create_index(
        op.f("ix_stream_failures_anime_id"), "stream_failures", ["anime_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stream_failures_anime_id"), table_name="stream_failures")
    op.drop_table("stream_failures")
    # ### end Alembic commands ###
