"""airing schedule

Revision ID: 3501f694f025
Revises: 686316838aca
Create Date: 2026-09-25 12:50:25.133657

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3501f694f025"
down_revision: str | Sequence[str] | None = "686316838aca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airing_schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anime_id", sa.Integer(), nullable=False),
        sa.Column("episode", sa.Integer(), nullable=False),
        sa.Column("airing_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_airing_schedule")),
        sa.UniqueConstraint(
            "anime_id", "episode", name=op.f("uq_airing_schedule_anime_id_episode")
        ),
    )
    op.create_index(
        op.f("ix_airing_schedule_airing_at"), "airing_schedule", ["airing_at"], unique=False
    )
    op.create_index(
        op.f("ix_airing_schedule_anime_id"), "airing_schedule", ["anime_id"], unique=False
    )
    op.add_column("anime", sa.Column("next_episode", sa.Integer(), nullable=True))
    op.add_column("anime", sa.Column("next_episode_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "anime", sa.Column("airing_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("anime", "airing_checked_at")
    op.drop_column("anime", "next_episode_at")
    op.drop_column("anime", "next_episode")
    op.drop_index(op.f("ix_airing_schedule_anime_id"), table_name="airing_schedule")
    op.drop_index(op.f("ix_airing_schedule_airing_at"), table_name="airing_schedule")
    op.drop_table("airing_schedule")
    # ### end Alembic commands ###
