"""anime catalogue

Revision ID: 686316838aca
Revises: 34a54ec4a8a0
Create Date: 2026-09-25 12:22:58.258320

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "686316838aca"
down_revision: str | Sequence[str] | None = "34a54ec4a8a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("anime", sa.Column("alt_titles", sa.JSON(), server_default="[]", nullable=False))
    op.add_column("anime", sa.Column("mal_details_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("anime", sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Shows with MAL's member count came from MAL since the details were stored.
    op.execute("UPDATE anime SET mal_details_at = updated_at WHERE num_list_users IS NOT NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("anime", "enriched_at")
    op.drop_column("anime", "mal_details_at")
    op.drop_column("anime", "alt_titles")
    # ### end Alembic commands ###
