"""anime details and taste models

Revision ID: 9680d567f63d
Revises: 41488332a49c
Create Date: 2026-09-25 10:09:09.477469

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9680d567f63d"
down_revision: str | Sequence[str] | None = "41488332a49c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taste_models",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("fitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_taste_models_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_taste_models")),
    )
    op.add_column("anime", sa.Column("genre_tags", sa.JSON(), server_default="[]", nullable=False))
    op.add_column("anime", sa.Column("studios", sa.JSON(), server_default="[]", nullable=False))
    op.add_column("anime", sa.Column("source", sa.String(length=30), nullable=True))
    op.add_column("anime", sa.Column("rating", sa.String(length=10), nullable=True))
    op.add_column("anime", sa.Column("num_list_users", sa.Integer(), nullable=True))
    op.add_column("anime", sa.Column("num_scoring_users", sa.Integer(), nullable=True))
    op.add_column("anime", sa.Column("rank", sa.Integer(), nullable=True))
    op.add_column("anime", sa.Column("average_episode_duration", sa.Integer(), nullable=True))
    op.add_column("anime", sa.Column("start_year", sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # Cached shows lack the new details: mark them stale so they're fetched from MAL again.
    op.execute("UPDATE anime SET updated_at = '2000-01-01'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("anime", "start_year")
    op.drop_column("anime", "average_episode_duration")
    op.drop_column("anime", "rank")
    op.drop_column("anime", "num_scoring_users")
    op.drop_column("anime", "num_list_users")
    op.drop_column("anime", "rating")
    op.drop_column("anime", "source")
    op.drop_column("anime", "studios")
    op.drop_column("anime", "genre_tags")
    op.drop_table("taste_models")
    # ### end Alembic commands ###
