"""cached episode sources

Revision ID: d433df11cc55
Revises: 931fa29389bd
Create Date: 2026-09-24 16:31:58.921057

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d433df11cc55"
down_revision: str | Sequence[str] | None = "931fa29389bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "episode_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anime_id", sa.Integer(), nullable=False),
        sa.Column("episode", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("option_id", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("resolved", sa.JSON(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_episode_sources")),
        sa.UniqueConstraint(
            "anime_id",
            "episode",
            "option_id",
            name=op.f("uq_episode_sources_anime_id_episode_option_id"),
        ),
    )
    op.create_index(
        op.f("ix_episode_sources_anime_id"), "episode_sources", ["anime_id"], unique=False
    )
    op.create_table(
        "source_scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anime_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("episodes", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_scans")),
        sa.UniqueConstraint("anime_id", "provider", name=op.f("uq_source_scans_anime_id_provider")),
    )
    op.create_index(op.f("ix_source_scans_anime_id"), "source_scans", ["anime_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_scans_anime_id"), table_name="source_scans")
    op.drop_table("source_scans")
    op.drop_index(op.f("ix_episode_sources_anime_id"), table_name="episode_sources")
    op.drop_table("episode_sources")
    # ### end Alembic commands ###
