"""playback positions

Revision ID: 09bb4dcd6ff1
Revises: 3501f694f025
Create Date: 2026-09-25 15:13:55.915412

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09bb4dcd6ff1"
down_revision: str | Sequence[str] | None = "3501f694f025"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playback_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("anime_id", sa.Integer(), nullable=False),
        sa.Column("episode", sa.Integer(), nullable=False),
        sa.Column("position_s", sa.Float(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_playback_positions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playback_positions")),
        sa.UniqueConstraint(
            "user_id", "anime_id", name=op.f("uq_playback_positions_user_id_anime_id")
        ),
    )
    op.create_index(
        op.f("ix_playback_positions_user_id"), "playback_positions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_playback_positions_user_id"), table_name="playback_positions")
    op.drop_table("playback_positions")
    # ### end Alembic commands ###
