"""analysis job language

Revision ID: 18334e013e3c
Revises: 18e1d75f35f9
Create Date: 2026-09-24 21:13:58.454410

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18334e013e3c"
down_revision: str | Sequence[str] | None = "18e1d75f35f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analysis_jobs", sa.Column("language", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_jobs", "language")
    # ### end Alembic commands ###
