"""connections

Revision ID: e3141b1737db
Revises: 09bb4dcd6ff1
Create Date: 2026-09-25 15:43:33.478429

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3141b1737db"
down_revision: str | Sequence[str] | None = "09bb4dcd6ff1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connection_invites",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_connection_invites_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_connection_invites")),
    )
    op.create_index(
        op.f("ix_connection_invites_user_id"), "connection_invites", ["user_id"], unique=False
    )
    op.create_table(
        "connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_a_id", sa.Integer(), nullable=False),
        sa.Column("user_b_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_a_id"],
            ["users.id"],
            name=op.f("fk_connections_user_a_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_b_id"],
            ["users.id"],
            name=op.f("fk_connections_user_b_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connections")),
        sa.UniqueConstraint(
            "user_a_id", "user_b_id", name=op.f("uq_connections_user_a_id_user_b_id")
        ),
    )
    op.create_index(op.f("ix_connections_user_a_id"), "connections", ["user_a_id"], unique=False)
    op.create_index(op.f("ix_connections_user_b_id"), "connections", ["user_b_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_connections_user_b_id"), table_name="connections")
    op.drop_index(op.f("ix_connections_user_a_id"), table_name="connections")
    op.drop_table("connections")
    op.drop_index(op.f("ix_connection_invites_user_id"), table_name="connection_invites")
    op.drop_table("connection_invites")
    # ### end Alembic commands ###
