"""analysis job options

Revision ID: e6e2792e5b87
Revises: 7aa62b2f7017
Create Date: 2026-09-24 22:52:51.883571

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6e2792e5b87"
down_revision: str | Sequence[str] | None = "7aa62b2f7017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_jobs",
        sa.Column("compare", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "analysis_jobs",
        sa.Column("redownload", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_jobs", "redownload")
    op.drop_column("analysis_jobs", "compare")
    # ### end Alembic commands ###
