"""episode fingerprints

Revision ID: 384a9518d95d
Revises: 1895a32f9087
Create Date: 2026-09-24 22:07:40.502599

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "384a9518d95d"
down_revision: str | Sequence[str] | None = "1895a32f9087"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "episode_fingerprints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anime_id", sa.Integer(), nullable=False),
        sa.Column("episode", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("hashes", sa.LargeBinary(), nullable=False),
        sa.Column("valid", sa.LargeBinary(), nullable=False),
        sa.Column("frames", sa.Integer(), nullable=False),
        sa.Column("hop_seconds", sa.Float(), nullable=False),
        sa.Column("compared_with", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_episode_fingerprints")),
        sa.UniqueConstraint(
            "anime_id", "episode", name=op.f("uq_episode_fingerprints_anime_id_episode")
        ),
    )
    op.create_index(
        op.f("ix_episode_fingerprints_anime_id"), "episode_fingerprints", ["anime_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_episode_fingerprints_anime_id"), table_name="episode_fingerprints")
    op.drop_table("episode_fingerprints")
    # ### end Alembic commands ###
