"""reference segments

Revision ID: 7aa62b2f7017
Revises: 384a9518d95d
Create Date: 2026-09-24 22:34:01.900290

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7aa62b2f7017"
down_revision: str | Sequence[str] | None = "384a9518d95d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reference_segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anime_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("source_episode", sa.Integer(), nullable=False),
        sa.Column("hashes", sa.LargeBinary(), nullable=False),
        sa.Column("valid", sa.LargeBinary(), nullable=False),
        sa.Column("frames", sa.Integer(), nullable=False),
        sa.Column("hop_seconds", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_segments")),
        sa.UniqueConstraint(
            "anime_id",
            "kind",
            "source_episode",
            name=op.f("uq_reference_segments_anime_id_kind_source_episode"),
        ),
    )
    op.create_index(
        op.f("ix_reference_segments_anime_id"), "reference_segments", ["anime_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reference_segments_anime_id"), table_name="reference_segments")
    op.drop_table("reference_segments")
    # ### end Alembic commands ###
