"""anime synopses

Revision ID: ea44f47caf5a
Revises: 9680d567f63d
Create Date: 2026-09-25 10:45:48.020575

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea44f47caf5a"
down_revision: str | Sequence[str] | None = "9680d567f63d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anime_synopses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anime_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anime_synopses")),
        sa.UniqueConstraint(
            "anime_id", "language", name=op.f("uq_anime_synopses_anime_id_language")
        ),
    )
    op.create_index(
        op.f("ix_anime_synopses_anime_id"), "anime_synopses", ["anime_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_anime_synopses_anime_id"), table_name="anime_synopses")
    op.drop_table("anime_synopses")
    # ### end Alembic commands ###
