"""resolved sources

Revision ID: 1895a32f9087
Revises: 18334e013e3c
Create Date: 2026-09-24 21:31:59.975196

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1895a32f9087"
down_revision: str | Sequence[str] | None = "18334e013e3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resolved_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anime_id", sa.Integer(), nullable=False),
        sa.Column("episode", sa.Integer(), nullable=False),
        sa.Column("option_id", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resolved_sources")),
        sa.UniqueConstraint(
            "anime_id",
            "episode",
            "option_id",
            name=op.f("uq_resolved_sources_anime_id_episode_option_id"),
        ),
    )
    op.create_index(
        op.f("ix_resolved_sources_anime_id"), "resolved_sources", ["anime_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_resolved_sources_anime_id"), table_name="resolved_sources")
    op.drop_table("resolved_sources")
    # ### end Alembic commands ###
