"""provider mappings and source language

Revision ID: 931fa29389bd
Revises: ea1a48ba82ab
Create Date: 2026-09-24 13:12:00.901692

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "931fa29389bd"
down_revision: str | Sequence[str] | None = "ea1a48ba82ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anime_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("episode_offset", sa.Integer(), nullable=False),
        sa.Column("manual", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_mappings")),
        sa.UniqueConstraint(
            "anime_id", "provider", name=op.f("uq_provider_mappings_anime_id_provider")
        ),
    )
    op.create_index(
        op.f("ix_provider_mappings_anime_id"), "provider_mappings", ["anime_id"], unique=False
    )
    op.add_column("stream_sources", sa.Column("language", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stream_sources", "language")
    op.drop_index(op.f("ix_provider_mappings_anime_id"), table_name="provider_mappings")
    op.drop_table("provider_mappings")
    # ### end Alembic commands ###
