"""analysis job started at

Revision ID: 41488332a49c
Revises: e6e2792e5b87
Create Date: 2026-09-24 23:35:33.195114

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41488332a49c"
down_revision: str | Sequence[str] | None = "e6e2792e5b87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_jobs", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_jobs", "started_at")
    # ### end Alembic commands ###
