// Generated by brand/build.py: the NotFlix logo's geometry (edit it there, not here).

/** The mark ("Catchlight") on a 256 grid: the screen, and its two catchlights. */
export const MARK_SCREEN = "M66 46H190A46 46 0 0 1 236 92V164A46 46 0 0 1 190 210H66A46 46 0 0 1 20 164V92A46 46 0 0 1 66 46Z";
export const MARK_LIGHTS = "M70.15 125.50A34 25 -35 1 0 125.85 86.50A34 25 -35 1 0 70.15 125.50ZM134 141A12 12 0 1 0 158 141A12 12 0 1 0 134 141Z";
/** The NOTFLIX wordmark: caps 80-176 on the same grid, 548 wide. */
export const WORDMARK = "M0 80h24v96h-24Z M48 80h24v96h-24Z M0.00 80.00L27.00 80.00L72.00 176.00L45.00 176.00Z M85 128A50 50 0 1 0 185 128A50 50 0 1 0 85 128Z M109 128A26 26 0 1 1 161 128A26 26 0 1 1 109 128Z M198 80h72v24h-72Z M222 80h24v96h-24Z M284 80h24v96h-24Z M284 80h62v24h-62Z M284 118h52v22h-52Z M360 80h24v96h-24Z M360 152h58v24h-58Z M432 80h24v96h-24Z M470.00 80.00L497.00 80.00L548.00 176.00L521.00 176.00Z M521.00 80.00L548.00 80.00L497.00 176.00L470.00 176.00Z";
export const WORDMARK_WIDTH = 548;
/** Horizontal lockup: the wordmark starts this far right of the symbol's origin. */
export const LOCKUP_WORD_X = 268;
/** The horizontal lockup's tight box (x, y, width, height). */
export const LOCKUP_VIEWBOX = "20 46 796 164";
